/* Extra Korean and Japanese copy for screens that were added after the first
 * language picker. Keys are visible English phrases used by localizePage(). */
(() => {
  const ko = {
    'Choose interface language': '인터페이스 언어 선택',
    'Let’s Q never asks Queuers for a phone number, email, or account. The Android app can show clearly labelled ads; available privacy choices are provided by Google where required.': 'Let’s Q는 대기자에게 전화번호, 이메일 또는 계정을 요구하지 않습니다. Android 앱에는 명확히 표시된 광고가 나올 수 있으며, 필요한 경우 Google이 개인정보 선택지를 제공합니다.',
    'Or enter queue code': '또는 대기열 코드 입력', 'e.g. Q7K2M9': '예: Q7K2M9', 'Join with code': '코드로 참여',
    'Codes begin with Q and use five letters or numbers. Capital and lowercase work the same.': '코드는 Q로 시작하며 숫자 또는 영문자 5개를 사용합니다. 대소문자는 구분하지 않습니다.',
    'Let someone else hold your place': '다른 사람에게 내 순서를 맡기기', 'They can scan this QR code to view your ticket’s live status and present its secret code when you are called.': '상대방은 이 QR 코드를 스캔하여 티켓의 실시간 상태를 확인하고, 호출되면 비밀 코드를 제시할 수 있습니다.', 'Only share with someone you trust. In the public app, the sharing link is revocable and expires when the ticket closes.': '신뢰하는 사람에게만 공유하세요. 정식 앱에서는 공유 링크를 취소할 수 있으며 티켓이 종료되면 만료됩니다.', 'Copy link': '링크 복사', 'Back to my ticket': '내 티켓으로 돌아가기',
    'RATE YOUR EXPERIENCE': '경험 평가', 'ANONYMOUS': '익명', 'How was your visit?': '방문 경험은 어떠셨나요?', 'One tap per question. No name, contact details, or ticket code is included in the report.': '질문마다 한 번씩 선택하세요. 보고서에는 이름, 연락처 또는 티켓 코드가 포함되지 않습니다.', 'How was your wait?': '대기 시간은 어떠셨나요?', 'How was the service?': '서비스는 어떠셨나요?', 'Would you return?': '다시 이용하시겠습니까?', 'Submit anonymous rating': '익명 평가 제출',
    'Queue joining hours': '대기열 참여 시간', 'People can join only during these local times. After the end time, you may still finish serving people already in line.': '사람들은 이 현지 시간에만 대기열에 참여할 수 있습니다. 종료 시간 후에도 이미 줄을 선 사람의 안내는 마칠 수 있습니다.', 'Start time': '시작 시간', 'End time': '종료 시간', 'The ticket closes after the first no-show.': '첫 번째 미도착 후 티켓이 종료됩니다.', 'The ticket keeps its number. After two deferrals, the third no-show closes it.': '티켓 번호는 유지됩니다. 두 번 뒤로 이동한 후 세 번째 미도착 시 종료됩니다.', 'Use this for a short grace period before the ticket is recalled.': '티켓을 다시 호출하기 전 짧은 유예 시간을 주려면 사용하세요.',
    'PAIR STAFF DEVICE': '직원 기기 연결', 'Give staff queue access': '직원에게 대기열 권한 부여', 'Use this on the staff member’s device so they can call tickets without signing in to your personal account.': '직원 기기에서 사용하면 개인 계정에 로그인하지 않고도 티켓을 호출할 수 있습니다.', 'Scan with the staff device. This pairing QR expires in 10 minutes and works once.': '직원 기기로 스캔하세요. 이 연결 QR은 10분 후 만료되며 한 번만 사용할 수 있습니다.', 'Or enter this PIN': '또는 이 PIN 입력', 'Revoke devices': '기기 연결 해제',
    'HOST · PRINT QUEUE QR': '호스트 · 대기열 QR 인쇄', 'Print a scan-to-join sheet': '스캔하여 참여하는 안내지 인쇄', 'Choose the paper size, then print the QR sheet for people waiting in line.': '용지 크기를 선택한 후 대기 중인 사람을 위한 QR 안내지를 인쇄하세요.', 'Print sheet': '안내지 인쇄',
    'PRIVACY PROMISE': '개인정보 보호 약속', 'PUBLIC VERSION': '공개 버전', 'Join a queue without handing over your identity.': '개인 정보를 넘기지 않고 대기열에 참여하세요.', 'For queuers:': '대기자용:', 'Clearly labelled ads.': '명확히 표시된 광고.', 'Minimal ticket data.': '최소한의 티켓 데이터.', 'Anonymous ratings.': '익명 평가.', 'Optional notifications.': '선택 알림.', 'Private notes are optional.': '개인 메모는 선택 사항입니다.', 'Privacy choices': '개인정보 선택',
    'Let’s Q does not ask for a name, phone number, email address, contact list, or social-media login. Your ticket uses only a queue number and a secret code that you choose.': 'Let’s Q는 이름, 전화번호, 이메일 주소, 연락처 목록 또는 소셜 미디어 로그인을 요구하지 않습니다. 티켓에는 대기열 번호와 직접 선택한 비밀 코드만 사용됩니다.', 'The free Android app can show Google AdMob ads. Depending on your region, Google may ask for consent and offers Privacy choices where required.': '무료 Android 앱에는 Google AdMob 광고가 표시될 수 있습니다. 지역에 따라 Google에서 동의를 요청하고 필요한 경우 개인정보 선택지를 제공합니다.', 'Host analytics use aggregate rating scores only. Do not include names, contact details, ticket codes, or device identifiers in the report.': '호스트 분석에는 종합 평가 점수만 사용합니다. 보고서에는 이름, 연락처, 티켓 코드 또는 기기 식별자를 포함하지 않습니다.',
    'Your ticket': '내 티켓', 'JOIN THIS QUEUE': '이 대기열 참여', 'Queue is full': '대기열이 가득 찼습니다.', 'Queue is empty.': '대기열이 비어 있습니다.', 'UP NEXT': '다음 순서', 'ACTIVE': '대기 중', 'Ticket details hidden until called': '호출될 때까지 티켓 정보가 숨겨집니다.', 'VISIT COMPLETE': '방문 완료', 'Thanks for visiting.': '방문해 주셔서 감사합니다.', 'Your anonymous rating was added to the aggregate report.': '익명 평가가 종합 보고서에 추가되었습니다.', 'Would you like to rate the wait and service?': '대기 시간과 서비스를 평가하시겠습니까?', 'View rating': '평가 보기',
    'YOUR TURN — head to the counter': '차례입니다 — 카운터로 오세요', 'PLEASE COME TO THE COUNTER': '카운터로 와 주세요', 'HELD — WE WILL CALL YOU AGAIN': '보류됨 — 다시 호출합니다', 'TICKET CANCELLED': '티켓 취소됨', 'WAITING —': '대기 중 —', 'est. wait': '예상 대기', 'ahead': '명 앞', 'now': '지금', 'held': '보류', 'Share ticket by QR': 'QR로 티켓 공유',
    'HOST CONSOLE': '호스트 콘솔', 'Called ticket code:': '호출한 티켓 코드:', 'View analytics': '분석 보기', 'Ad-free active': '광고 없음 활성화', 'Ad-free + analytics · $1/month': '광고 없음 + 분석 · 월 $1', 'Nobody is waiting.': '대기 중인 사람이 없습니다.', 'Saved queue': '저장된 대기열', 'Total queued': '전체 대기 인원', 'Avg. wait': '평균 대기', 'No-show rate': '미도착 비율', 'Anonymous experience ratings': '익명 경험 평가', 'No ratings submitted yet.': '아직 제출된 평가가 없습니다.', 'Back to host': '호스트로 돌아가기', 'Start a new queue': '새 대기열 시작', 'End queue': '대기열 종료', 'QR code': 'QR 코드', 'Live queue code:': '실시간 대기열 코드:',
    'No full-screen ads are shown when the app opens.': '앱을 열 때 전체 화면 광고는 표시되지 않습니다.', 'This device is ad-free.': '이 기기에는 광고가 없습니다.', 'Go ad-free, with analytics included.': '광고 없이 이용하고 분석도 받으세요.', 'Language changed.': '언어가 변경되었습니다.', 'Thank you. Your anonymous rating was added.': '감사합니다. 익명 평가가 추가되었습니다.', 'Choose one score for each question.': '각 질문에 점수 하나를 선택하세요.'
  };
  const ja = {
    'Choose interface language': '表示言語を選択',
    'Let’s Q never asks Queuers for a phone number, email, or account. The Android app can show clearly labelled ads; available privacy choices are provided by Google where required.': 'Let’s Q は利用者に電話番号、メールアドレス、アカウントを求めません。Android アプリには明確に表示された広告が出ることがあり、必要な場合は Google がプライバシーの選択肢を提供します。',
    'Or enter queue code': 'または待機列コードを入力', 'e.g. Q7K2M9': '例：Q7K2M9', 'Join with code': 'コードで参加', 'Codes begin with Q and use five letters or numbers. Capital and lowercase work the same.': 'コードは Q で始まり、英字または数字を5文字使用します。大文字と小文字は区別されません。',
    'Let someone else hold your place': '他の人に順番を預ける', 'They can scan this QR code to view your ticket’s live status and present its secret code when you are called.': 'この QR コードを読み取ると、相手はチケットの現在の状態を確認し、呼ばれたときに秘密コードを提示できます。', 'Only share with someone you trust. In the public app, the sharing link is revocable and expires when the ticket closes.': '信頼できる相手とのみ共有してください。正式版では共有リンクを無効にでき、チケットが終了すると期限切れになります。', 'Copy link': 'リンクをコピー', 'Back to my ticket': '自分のチケットに戻る',
    'RATE YOUR EXPERIENCE': '体験を評価', 'ANONYMOUS': '匿名', 'How was your visit?': 'ご利用はいかがでしたか？', 'One tap per question. No name, contact details, or ticket code is included in the report.': '各質問で1つ選択してください。レポートに氏名、連絡先、チケットコードは含まれません。', 'How was your wait?': '待ち時間はいかがでしたか？', 'How was the service?': 'サービスはいかがでしたか？', 'Would you return?': 'また利用したいですか？', 'Submit anonymous rating': '匿名評価を送信',
    'Queue joining hours': '待機列の参加時間', 'People can join only during these local times. After the end time, you may still finish serving people already in line.': '利用者はこの現地時間内だけ待機列に参加できます。終了時刻後も、すでに並んでいる人の対応は完了できます。', 'Start time': '開始時刻', 'End time': '終了時刻', 'The ticket closes after the first no-show.': '最初の不在でチケットは終了します。', 'The ticket keeps its number. After two deferrals, the third no-show closes it.': 'チケット番号は維持されます。2回後ろに移動した後、3回目の不在で終了します。', 'Use this for a short grace period before the ticket is recalled.': 'チケットを再度呼び出す前に短い猶予を与える場合に使います。',
    'PAIR STAFF DEVICE': 'スタッフ端末を連携', 'Give staff queue access': 'スタッフに待機列の操作権限を付与', 'Use this on the staff member’s device so they can call tickets without signing in to your personal account.': 'スタッフの端末で使用すると、個人アカウントにログインせずにチケットを呼び出せます。', 'Scan with the staff device. This pairing QR expires in 10 minutes and works once.': 'スタッフ端末で読み取ってください。この連携 QR は10分で期限切れになり、一度だけ使えます。', 'Or enter this PIN': 'またはこの PIN を入力', 'Revoke devices': '端末の連携を解除',
    'HOST · PRINT QUEUE QR': '主催者 · 待機列 QR を印刷', 'Print a scan-to-join sheet': '読み取り用の参加シートを印刷', 'Choose the paper size, then print the QR sheet for people waiting in line.': '用紙サイズを選び、待機列に並ぶ人用の QR シートを印刷してください。', 'Print sheet': 'シートを印刷',
    'PRIVACY PROMISE': 'プライバシーの約束', 'PUBLIC VERSION': '公開版', 'Join a queue without handing over your identity.': '個人情報を渡さずに待機列へ参加できます。', 'For queuers:': '利用者向け：', 'Clearly labelled ads.': '明確に表示された広告。', 'Minimal ticket data.': '最小限のチケットデータ。', 'Anonymous ratings.': '匿名評価。', 'Optional notifications.': '任意の通知。', 'Private notes are optional.': '個別メモは任意です。', 'Privacy choices': 'プライバシーの選択',
    'Let’s Q does not ask for a name, phone number, email address, contact list, or social-media login. Your ticket uses only a queue number and a secret code that you choose.': 'Let’s Q は氏名、電話番号、メールアドレス、連絡先リスト、SNS ログインを求めません。チケットには待機列番号と自分で選んだ秘密コードだけを使います。', 'The free Android app can show Google AdMob ads. Depending on your region, Google may ask for consent and offers Privacy choices where required.': '無料の Android アプリには Google AdMob 広告が表示される場合があります。地域によっては Google が同意を求め、必要な場合はプライバシーの選択肢を提供します。', 'Host analytics use aggregate rating scores only. Do not include names, contact details, ticket codes, or device identifiers in the report.': '主催者の分析では集計した評価点だけを使用します。レポートに氏名、連絡先、チケットコード、端末識別子は含めません。',
    'Your ticket': 'あなたのチケット', 'JOIN THIS QUEUE': 'この待機列に参加', 'Queue is full': '待機列は満員です。', 'Queue is empty.': '待機列は空です。', 'UP NEXT': '次の順番', 'ACTIVE': '待機中', 'Ticket details hidden until called': '呼ばれるまでチケットの詳細は非表示です。', 'VISIT COMPLETE': 'ご利用完了', 'Thanks for visiting.': 'ご利用ありがとうございました。', 'Your anonymous rating was added to the aggregate report.': '匿名評価が集計レポートに追加されました。', 'Would you like to rate the wait and service?': '待ち時間とサービスを評価しますか？', 'View rating': '評価を見る',
    'YOUR TURN — head to the counter': 'あなたの番です — カウンターへお越しください', 'PLEASE COME TO THE COUNTER': 'カウンターへお越しください', 'HELD — WE WILL CALL YOU AGAIN': '保留中 — もう一度お呼びします', 'TICKET CANCELLED': 'チケットは取り消されました', 'WAITING —': '待機中 —', 'est. wait': '予想待ち時間', 'ahead': '人前', 'now': '現在', 'held': '保留', 'Share ticket by QR': 'QR でチケットを共有',
    'HOST CONSOLE': '主催者コンソール', 'Called ticket code:': '呼び出し中のチケットコード：', 'View analytics': '分析を見る', 'Ad-free active': '広告なしが有効', 'Ad-free + analytics · $1/month': '広告なし + 分析 · 月額 $1', 'Nobody is waiting.': '待っている人はいません。', 'Saved queue': '保存した待機列', 'Total queued': '合計参加者数', 'Avg. wait': '平均待ち時間', 'No-show rate': '不在率', 'Anonymous experience ratings': '匿名の体験評価', 'No ratings submitted yet.': 'まだ評価は送信されていません。', 'Back to host': '主催者に戻る', 'Start a new queue': '新しい待機列を開始', 'End queue': '待機列を終了', 'QR code': 'QR コード', 'Live queue code:': 'ライブ待機列コード：',
    'No full-screen ads are shown when the app opens.': 'アプリを開くときに全画面広告は表示されません。', 'This device is ad-free.': 'この端末は広告なしです。', 'Go ad-free, with analytics included.': '広告なしで、分析も利用できます。', 'Language changed.': '言語を変更しました。', 'Thank you. Your anonymous rating was added.': 'ありがとうございました。匿名評価を追加しました。', 'Choose one score for each question.': '各質問で1つの点数を選んでください。'
  };
  // Complete copy for the app-shaped screens. The original dictionaries cover
  // the older queue flows; this set covers the new Home, scanner, setup,
  // appearance, notification, QR, and report UI as well.
  const appCopy = {
    es: {
      'Language': 'Idioma', 'Choose language': 'Elegir idioma', 'Choose interface language': 'Elegir idioma de la aplicación', 'Notifications': 'Notificaciones', 'LET’S Q': 'LET’S Q',
      'Queuer': 'Cliente', 'Q list': 'Mis colas', 'Home': 'Inicio', 'Host': 'Anfitrión', 'Reports': 'Informes',
      'Private queues.': 'Colas privadas.', 'No account required.': 'No se necesita cuenta.', 'Join a line with a QR or short code, or set up a queue from the same app.': 'Únete a una fila con un QR o código corto, o crea una cola desde la misma aplicación.',
      'Join a queue': 'Unirse a una cola', 'Set up a queue': 'Crear una cola', 'Scan a QR or enter a code': 'Escanea un QR o escribe un código', 'Create and manage your own line': 'Crea y administra tu propia fila',
      'App appearance': 'Apariencia de la aplicación', 'Your privacy comes first': 'Tu privacidad es lo primero', 'Choose your Host and Queuer palettes.': 'Elige las paletas del anfitrión y del cliente.', 'No name, phone number, email, or Queuer account.': 'Sin nombre, teléfono, correo electrónico ni cuenta de cliente.',
      'Scan the Host QR or enter a short code. No account or personal details are required.': 'Escanea el QR del anfitrión o escribe un código corto. No se requiere cuenta ni datos personales.', 'Ready to scan': 'Listo para escanear', 'Camera is off. Start scanning when you are ready.': 'La cámara está apagada. Inicia el escaneo cuando estés listo.', 'Start camera scanner': 'Abrir cámara', 'or': 'o', 'Queue code': 'Código de cola', 'Join with code': 'Unirse con código', 'Codes start with Q and use five letters or numbers. Uppercase and lowercase work the same.': 'Los códigos empiezan con Q y usan cinco letras o números. No distinguen mayúsculas.',
      'Private by design': 'Privado por diseño', 'No name, phone number, email, or Queuer account is needed.': 'No se necesita nombre, teléfono, correo electrónico ni cuenta.',
      'My queues': 'Mis colas', 'Join another': 'Unirse a otra', 'Waiting': 'En espera', 'Ready': 'Listo', 'Past': 'Anteriores', 'All': 'Todas', 'No saved queues yet.': 'Aún no hay colas guardadas.', 'Scan a Host QR or enter a queue code. You can hold places in more than one queue at a time.': 'Escanea un QR de anfitrión o escribe un código. Puedes tener lugares en más de una cola a la vez.',
      'APPEARANCE': 'APARIENCIA', 'Make Let’s Q yours': 'Haz Let’s Q a tu gusto', 'Choose from ten polished two-color palettes. Your Host and Queuer views can use different palettes.': 'Elige entre diez paletas de dos colores. Las vistas de anfitrión y cliente pueden usar paletas diferentes.', 'Queuer palette': 'Paleta de cliente', 'Host palette': 'Paleta de anfitrión',
      'Ocean': 'Océano', 'Sky': 'Cielo', 'Indigo': 'Índigo', 'Violet': 'Violeta', 'Berry': 'Baya', 'Coral': 'Coral', 'Sunset': 'Atardecer', 'Citrus': 'Cítrico', 'Forest': 'Bosque', 'Mint': 'Menta',
      'HOST': 'ANFITRIÓN', 'Set up your queue': 'Configura tu cola', 'Use a short public description of the booth or event. Do not put personal information here.': 'Usa una descripción pública corta del puesto o evento. No escribas información personal aquí.', 'Booth or event name': 'Nombre del puesto o evento', 'Queue name': 'Nombre de la cola', 'Queue photo (optional)': 'Foto de la cola (opcional)', 'Take a photo': 'Tomar una foto', 'Choose from device': 'Elegir del dispositivo', 'No photo selected.': 'No se eligió ninguna foto.',
      'Queue dates and hours': 'Fechas y horarios de la cola', 'Start date': 'Fecha de inicio', 'End date': 'Fecha de fin', 'Start time': 'Hora de inicio', 'End time': 'Hora de fin', 'Planned orders (optional)': 'Servicios previstos (opcional)', 'No limit': 'Sin límite', 'This is only a planning number. Joining stays unlimited.': 'Es solo una cifra de planificación. La cola sigue siendo ilimitada.', 'When a called ticket does not arrive': 'Cuando no llega un turno llamado', 'Cancel immediately': 'Cancelar de inmediato', 'Move to the back twice, then cancel': 'Mover al final dos veces y luego cancelar', 'Hold for': 'Esperar', 'minutes, twice, then cancel': 'minutos, dos veces y luego cancelar', 'Start this queue': 'Iniciar esta cola',
      'Queue QR code': 'Código QR de la cola', 'Choose a size, then save a file or show the code full screen.': 'Elige un tamaño y guarda un archivo o muestra el código a pantalla completa.', 'Letter': 'Carta', 'Download JPG': 'Descargar JPG', 'Download PDF': 'Descargar PDF', 'Full screen': 'Pantalla completa',
      'NOTIFICATIONS': 'NOTIFICACIONES', 'Nothing to catch up on': 'No hay novedades', 'Let’s Q does not require notification permission or a phone number. Check My queues any time to see the latest live status.': 'Let’s Q no requiere permiso de notificaciones ni teléfono. Revisa Mis colas en cualquier momento para ver el estado.', 'Open Q list': 'Abrir Mis colas',
      'Unlock your queue report': 'Desbloquea el informe de tu cola', 'Reports show only combined counts, wait times, no-show totals, and anonymous rating averages.': 'Los informes muestran solo totales, tiempos de espera, ausencias y promedios de valoraciones anónimas.', 'Watch a sponsor video': 'Ver un video patrocinado', 'One optional rewarded video unlocks this report once a rewarded ad unit is connected.': 'Un video recompensado opcional desbloquea este informe cuando se conecte una unidad de anuncios recompensados.', 'Go ad-free + analytics': 'Sin anuncios + análisis', 'Language changed.': 'Idioma cambiado.'
    },
    'zh-Hant': {
      'Language': '語言', 'Choose language': '選擇語言', 'Choose interface language': '選擇介面語言', 'Notifications': '通知', 'Queuer': '排隊者', 'Q list': '我的隊列', 'Home': '首頁', 'Host': '主辦方', 'Reports': '報告',
      'Private queues.': '私密隊列。', 'No account required.': '無需帳戶。', 'Join a line with a QR or short code, or set up a queue from the same app.': '使用 QR Code 或短代碼加入隊列，也可在同一個應用程式中建立隊列。', 'Join a queue': '加入隊列', 'Set up a queue': '建立隊列', 'Scan a QR or enter a code': '掃描 QR Code 或輸入代碼', 'Create and manage your own line': '建立並管理自己的隊列',
      'App appearance': '應用程式外觀', 'Your privacy comes first': '你的隱私優先', 'Choose your Host and Queuer palettes.': '選擇主辦方與排隊者的配色。', 'No name, phone number, email, or Queuer account.': '不需姓名、電話、電子郵件或排隊者帳戶。',
      'Scan the Host QR or enter a short code. No account or personal details are required.': '掃描主辦方的 QR Code 或輸入短代碼。不需要帳戶或個人資料。', 'Ready to scan': '準備掃描', 'Camera is off. Start scanning when you are ready.': '相機已關閉，準備好後開始掃描。', 'Start camera scanner': '開啟相機掃描', 'or': '或', 'Queue code': '隊列代碼', 'Join with code': '使用代碼加入', 'Codes start with Q and use five letters or numbers. Uppercase and lowercase work the same.': '代碼以 Q 開頭，後接五個字母或數字，不分大小寫。', 'Private by design': '隱私優先設計', 'No name, phone number, email, or Queuer account is needed.': '無需姓名、電話、電子郵件或排隊者帳戶。',
      'My queues': '我的隊列', 'Join another': '加入另一個', 'Waiting': '等待中', 'Ready': '已叫到', 'Past': '已結束', 'All': '全部', 'No saved queues yet.': '尚未儲存任何隊列。', 'Scan a Host QR or enter a queue code. You can hold places in more than one queue at a time.': '掃描主辦方 QR Code 或輸入隊列代碼。你可以同時保留多個隊列的位置。',
      'APPEARANCE': '外觀', 'Make Let’s Q yours': '打造你的 Let’s Q', 'Choose from ten polished two-color palettes. Your Host and Queuer views can use different palettes.': '從十種精心搭配的雙色配色中選擇。主辦方與排隊者可以使用不同配色。', 'Queuer palette': '排隊者配色', 'Host palette': '主辦方配色', 'Ocean': '海洋', 'Sky': '天空', 'Indigo': '靛藍', 'Violet': '紫羅蘭', 'Berry': '莓果', 'Coral': '珊瑚', 'Sunset': '日落', 'Citrus': '柑橘', 'Forest': '森林', 'Mint': '薄荷',
      'HOST': '主辦方', 'Set up your queue': '設定你的隊列', 'Use a short public description of the booth or event. Do not put personal information here.': '使用攤位或活動的簡短公開說明。請勿在此填入個人資料。', 'Booth or event name': '攤位或活動名稱', 'Queue name': '隊列名稱', 'Queue photo (optional)': '隊列照片（選填）', 'Take a photo': '拍照', 'Choose from device': '從裝置選擇', 'No photo selected.': '尚未選擇照片。', 'Queue dates and hours': '隊列日期與時間', 'Start date': '開始日期', 'End date': '結束日期', 'Start time': '開始時間', 'End time': '結束時間', 'Planned orders (optional)': '預計服務人數（選填）', 'No limit': '無限制', 'This is only a planning number. Joining stays unlimited.': '這只是規劃數字，加入人數不受限制。', 'When a called ticket does not arrive': '叫號後未到場時', 'Cancel immediately': '立即取消', 'Move to the back twice, then cancel': '移到隊尾兩次後取消', 'Hold for': '保留', 'minutes, twice, then cancel': '分鐘，兩次後取消', 'Start this queue': '開始此隊列',
      'Queue QR code': '隊列 QR Code', 'Choose a size, then save a file or show the code full screen.': '選擇大小後儲存檔案，或全螢幕顯示代碼。', 'Letter': 'Letter 紙張', 'Download JPG': '下載 JPG', 'Download PDF': '下載 PDF', 'Full screen': '全螢幕', 'NOTIFICATIONS': '通知', 'Nothing to catch up on': '沒有新通知', 'Let’s Q does not require notification permission or a phone number. Check My queues any time to see the latest live status.': 'Let’s Q 不需要通知權限或電話號碼。隨時查看「我的隊列」即可取得最新狀態。', 'Open Q list': '開啟我的隊列', 'Unlock your queue report': '解鎖隊列報告', 'Reports show only combined counts, wait times, no-show totals, and anonymous rating averages.': '報告只顯示總數、等待時間、未到場總數與匿名評分平均值。', 'Watch a sponsor video': '觀看贊助影片', 'Go ad-free + analytics': '去廣告並查看分析', 'Language changed.': '語言已變更。'
    },
    'zh-Hans': {
      'Language': '语言', 'Choose language': '选择语言', 'Choose interface language': '选择界面语言', 'Notifications': '通知', 'Queuer': '排队者', 'Q list': '我的队列', 'Home': '首页', 'Host': '主办方', 'Reports': '报告',
      'Private queues.': '私密队列。', 'No account required.': '无需账户。', 'Join a line with a QR or short code, or set up a queue from the same app.': '使用二维码或短代码加入队列，也可在同一应用中创建队列。', 'Join a queue': '加入队列', 'Set up a queue': '创建队列', 'Scan a QR or enter a code': '扫描二维码或输入代码', 'Create and manage your own line': '创建并管理自己的队列', 'App appearance': '应用外观', 'Your privacy comes first': '你的隐私优先', 'Choose your Host and Queuer palettes.': '选择主办方和排队者的配色。', 'No name, phone number, email, or Queuer account.': '无需姓名、电话号码、邮箱或排队者账户。',
      'Scan the Host QR or enter a short code. No account or personal details are required.': '扫描主办方二维码或输入短代码。无需账户或个人资料。', 'Ready to scan': '准备扫描', 'Camera is off. Start scanning when you are ready.': '相机已关闭，准备好后开始扫描。', 'Start camera scanner': '打开相机扫描', 'or': '或', 'Queue code': '队列代码', 'Join with code': '使用代码加入', 'Codes start with Q and use five letters or numbers. Uppercase and lowercase work the same.': '代码以 Q 开头，后接五个字母或数字，不区分大小写。', 'Private by design': '隐私优先设计', 'No name, phone number, email, or Queuer account is needed.': '无需姓名、电话号码、邮箱或排队者账户。',
      'My queues': '我的队列', 'Join another': '加入另一个', 'Waiting': '等待中', 'Ready': '已叫到', 'Past': '已结束', 'All': '全部', 'No saved queues yet.': '暂时没有保存的队列。', 'Scan a Host QR or enter a queue code. You can hold places in more than one queue at a time.': '扫描主办方二维码或输入队列代码。你可以同时保留多个队列的位置。',
      'APPEARANCE': '外观', 'Make Let’s Q yours': '定制你的 Let’s Q', 'Choose from ten polished two-color palettes. Your Host and Queuer views can use different palettes.': '从十种精心搭配的双色配色中选择。主办方和排队者可以使用不同配色。', 'Queuer palette': '排队者配色', 'Host palette': '主办方配色', 'Ocean': '海洋', 'Sky': '天空', 'Indigo': '靛蓝', 'Violet': '紫罗兰', 'Berry': '莓果', 'Coral': '珊瑚', 'Sunset': '日落', 'Citrus': '柑橘', 'Forest': '森林', 'Mint': '薄荷',
      'HOST': '主办方', 'Set up your queue': '设置你的队列', 'Use a short public description of the booth or event. Do not put personal information here.': '使用摊位或活动的简短公开说明。请勿在此填写个人资料。', 'Booth or event name': '摊位或活动名称', 'Queue name': '队列名称', 'Queue photo (optional)': '队列照片（可选）', 'Take a photo': '拍照', 'Choose from device': '从设备选择', 'No photo selected.': '尚未选择照片。', 'Queue dates and hours': '队列日期和时间', 'Start date': '开始日期', 'End date': '结束日期', 'Start time': '开始时间', 'End time': '结束时间', 'Planned orders (optional)': '预计服务人数（可选）', 'No limit': '无限制', 'This is only a planning number. Joining stays unlimited.': '这只是规划人数，不会限制加入队列。', 'When a called ticket does not arrive': '叫号后未到场时', 'Cancel immediately': '立即取消', 'Move to the back twice, then cancel': '移到队尾两次后取消', 'Hold for': '保留', 'minutes, twice, then cancel': '分钟，两次后取消', 'Start this queue': '开始此队列',
      'Queue QR code': '队列二维码', 'Choose a size, then save a file or show the code full screen.': '选择尺寸后保存文件，或全屏显示代码。', 'Letter': 'Letter 纸张', 'Download JPG': '下载 JPG', 'Download PDF': '下载 PDF', 'Full screen': '全屏显示', 'NOTIFICATIONS': '通知', 'Nothing to catch up on': '没有新通知', 'Let’s Q does not require notification permission or a phone number. Check My queues any time to see the latest live status.': 'Let’s Q 不需要通知权限或电话号码。随时查看“我的队列”即可获取最新状态。', 'Open Q list': '打开我的队列', 'Unlock your queue report': '解锁队列报告', 'Reports show only combined counts, wait times, no-show totals, and anonymous rating averages.': '报告只显示总数、等待时间、未到场总数和匿名评分平均值。', 'Watch a sponsor video': '观看赞助视频', 'Go ad-free + analytics': '去广告并查看分析', 'Language changed.': '语言已更改。'
    },
    ko: {
      'Choose language': '언어 선택', 'Queuer': '대기자', 'Q list': '내 대기열', 'Reports': '보고서', 'Private queues.': '비공개 대기열.', 'No account required.': '계정이 필요 없습니다.', 'Join a line with a QR or short code, or set up a queue from the same app.': 'QR 또는 짧은 코드로 줄에 참여하거나 같은 앱에서 대기열을 만드세요.', 'Scan a QR or enter a code': 'QR을 스캔하거나 코드 입력', 'Create and manage your own line': '내 대기열 만들기 및 관리', 'Choose your Host and Queuer palettes.': '호스트와 대기자 팔레트를 선택하세요.', 'No name, phone number, email, or Queuer account.': '이름, 전화번호, 이메일 또는 대기자 계정이 필요 없습니다.',
      'Scan the Host QR or enter a short code. No account or personal details are required.': '호스트 QR을 스캔하거나 짧은 코드를 입력하세요. 계정이나 개인 정보는 필요 없습니다.', 'Ready to scan': '스캔 준비 완료', 'or': '또는', 'Queue code': '대기열 코드', 'Codes start with Q and use five letters or numbers. Uppercase and lowercase work the same.': '코드는 Q로 시작하고 숫자 또는 영문자 다섯 개를 사용합니다. 대소문자는 구분하지 않습니다.', 'Private by design': '개인정보 보호 설계', 'No name, phone number, email, or Queuer account is needed.': '이름, 전화번호, 이메일 또는 대기자 계정이 필요 없습니다.',
      'My queues': '내 대기열', 'Join another': '다른 대기열 참여', 'Waiting': '대기 중', 'Ready': '호출됨', 'Past': '지난 대기열', 'All': '전체', 'No saved queues yet.': '저장된 대기열이 아직 없습니다.', 'Scan a Host QR or enter a queue code. You can hold places in more than one queue at a time.': '호스트 QR을 스캔하거나 대기열 코드를 입력하세요. 한 번에 여러 대기열의 자리를 유지할 수 있습니다.',
      'APPEARANCE': '외관', 'Make Let’s Q yours': '나만의 Let’s Q 만들기', 'Choose from ten polished two-color palettes. Your Host and Queuer views can use different palettes.': '완성도 높은 10가지 두 색상 팔레트 중에서 선택하세요. 호스트와 대기자 화면은 서로 다른 팔레트를 사용할 수 있습니다.', 'Queuer palette': '대기자 팔레트', 'Host palette': '호스트 팔레트', 'Ocean': '오션', 'Sky': '스카이', 'Indigo': '인디고', 'Violet': '바이올렛', 'Berry': '베리', 'Coral': '코랄', 'Sunset': '선셋', 'Citrus': '시트러스', 'Forest': '포레스트', 'Mint': '민트',
      'Use a short public description of the booth or event. Do not put personal information here.': '부스 또는 행사를 짧게 공개 설명하세요. 개인 정보는 입력하지 마세요.', 'No photo selected.': '선택한 사진이 없습니다.', 'Queue dates and hours': '대기열 날짜와 시간', 'Planned orders (optional)': '예정 서비스 수(선택)', 'No limit': '제한 없음', 'This is only a planning number. Joining stays unlimited.': '계획을 위한 숫자일 뿐입니다. 참여 인원은 제한되지 않습니다.', 'Move to the back twice, then cancel': '뒤로 두 번 이동한 뒤 취소', 'Hold for': '보류', 'minutes, twice, then cancel': '분, 두 번 후 취소',
      'Queue QR code': '대기열 QR 코드', 'Choose a size, then save a file or show the code full screen.': '크기를 선택한 후 파일로 저장하거나 전체 화면으로 코드를 표시하세요.', 'Download JPG': 'JPG 다운로드', 'Download PDF': 'PDF 다운로드', 'Full screen': '전체 화면', 'NOTIFICATIONS': '알림', 'Nothing to catch up on': '새 알림이 없습니다.', 'Let’s Q does not require notification permission or a phone number. Check My queues any time to see the latest live status.': 'Let’s Q는 알림 권한이나 전화번호를 요구하지 않습니다. 언제든 내 대기열에서 최신 상태를 확인하세요.', 'Open Q list': '내 대기열 열기', 'Unlock your queue report': '대기열 보고서 잠금 해제', 'Reports show only combined counts, wait times, no-show totals, and anonymous rating averages.': '보고서에는 합계, 대기 시간, 미도착 총수 및 익명 평가 평균만 표시됩니다.', 'Watch a sponsor video': '스폰서 동영상 보기', 'Go ad-free + analytics': '광고 없음 + 분석'
    },
    ja: {
      'Choose language': '言語を選択', 'Queuer': '利用者', 'Q list': '自分の待機列', 'Reports': 'レポート', 'Private queues.': 'プライベート待機列。', 'No account required.': 'アカウント不要。', 'Join a line with a QR or short code, or set up a queue from the same app.': 'QR または短いコードで待機列に参加するか、同じアプリで待機列を作成できます。', 'Scan a QR or enter a code': 'QR を読み取るかコードを入力', 'Create and manage your own line': '自分の待機列を作成・管理', 'Choose your Host and Queuer palettes.': '主催者用と利用者用の配色を選びます。', 'No name, phone number, email, or Queuer account.': '氏名、電話番号、メールアドレス、利用者アカウントは不要です。',
      'Scan the Host QR or enter a short code. No account or personal details are required.': '主催者の QR を読み取るか短いコードを入力してください。アカウントや個人情報は不要です。', 'Ready to scan': '読み取り準備完了', 'or': 'または', 'Queue code': '待機列コード', 'Codes start with Q and use five letters or numbers. Uppercase and lowercase work the same.': 'コードは Q で始まり、英字または数字を5文字使用します。大文字と小文字は区別されません。', 'Private by design': 'プライバシー重視の設計', 'No name, phone number, email, or Queuer account is needed.': '氏名、電話番号、メールアドレス、利用者アカウントは不要です。',
      'My queues': '自分の待機列', 'Join another': '別の待機列に参加', 'Waiting': '待機中', 'Ready': '呼び出し済み', 'Past': '完了', 'All': 'すべて', 'No saved queues yet.': '保存された待機列はまだありません。', 'Scan a Host QR or enter a queue code. You can hold places in more than one queue at a time.': '主催者の QR を読み取るか待機列コードを入力してください。複数の待機列で同時に順番を保持できます。',
      'APPEARANCE': '外観', 'Make Let’s Q yours': 'Let’s Q を自分好みに', 'Choose from ten polished two-color palettes. Your Host and Queuer views can use different palettes.': '洗練された10種類の2色パレットから選べます。主催者画面と利用者画面で別々のパレットを使えます。', 'Queuer palette': '利用者の配色', 'Host palette': '主催者の配色', 'Ocean': 'オーシャン', 'Sky': 'スカイ', 'Indigo': 'インディゴ', 'Violet': 'バイオレット', 'Berry': 'ベリー', 'Coral': 'コーラル', 'Sunset': 'サンセット', 'Citrus': 'シトラス', 'Forest': 'フォレスト', 'Mint': 'ミント',
      'Use a short public description of the booth or event. Do not put personal information here.': 'ブースやイベントの短い公開説明を入力してください。個人情報は入力しないでください。', 'No photo selected.': '写真は選択されていません。', 'Queue dates and hours': '待機列の日付と時間', 'Planned orders (optional)': '予定対応数（任意）', 'No limit': '上限なし', 'This is only a planning number. Joining stays unlimited.': 'これは計画用の数字です。参加人数は無制限のままです。', 'Move to the back twice, then cancel': '2回最後尾へ移動してから取り消す', 'Hold for': '保留', 'minutes, twice, then cancel': '分、2回後に取り消す',
      'Queue QR code': '待機列 QR コード', 'Choose a size, then save a file or show the code full screen.': 'サイズを選び、ファイルとして保存するかコードを全画面で表示します。', 'Download JPG': 'JPG をダウンロード', 'Download PDF': 'PDF をダウンロード', 'Full screen': '全画面', 'NOTIFICATIONS': '通知', 'Nothing to catch up on': '新しいお知らせはありません。', 'Let’s Q does not require notification permission or a phone number. Check My queues any time to see the latest live status.': 'Let’s Q は通知権限や電話番号を求めません。いつでも自分の待機列で最新の状態を確認できます。', 'Open Q list': '自分の待機列を開く', 'Unlock your queue report': '待機列レポートを解除', 'Reports show only combined counts, wait times, no-show totals, and anonymous rating averages.': 'レポートには合計数、待ち時間、不在数、匿名評価の平均のみが表示されます。', 'Watch a sponsor video': 'スポンサー動画を見る', 'Go ad-free + analytics': '広告なし + 分析'
    }
  };
  // These are the remaining phrases from the live-ticket, rating, host-console,
  // staff-pairing, privacy, and subscription screens.  They are kept separate
  // from the shell copy above so every route can use the same text-node
  // translator in index.html.
  const legacySpanishCopy = {
    'Or enter queue code': 'O escribe el código de la cola', 'e.g. Q7K2M9': 'p. ej., Q7K2M9',
    'Codes begin with Q and use five letters or numbers. Capital and lowercase work the same.': 'Los códigos empiezan con Q y usan cinco letras o números. No distinguen mayúsculas.',
    'Let someone else hold your place': 'Deja que otra persona guarde tu lugar', 'They can scan this QR code to view your ticket’s live status and present its secret code when you are called.': 'Pueden escanear este QR para ver el estado en vivo de tu turno y mostrar el código secreto cuando te llamen.', 'Only share with someone you trust. In the public app, the sharing link is revocable and expires when the ticket closes.': 'Compártelo solo con alguien de confianza. En la aplicación pública, el enlace se puede revocar y vence cuando el turno se cierra.', 'Copy link': 'Copiar enlace', 'Back to my ticket': 'Volver a mi turno',
    'RATE YOUR EXPERIENCE': 'CALIFICA TU EXPERIENCIA', 'ANONYMOUS': 'ANÓNIMO', 'How was your visit?': '¿Cómo fue tu visita?', 'One tap per question. No name, contact details, or ticket code is included in the report.': 'Una respuesta por pregunta. El informe no incluye nombre, datos de contacto ni código de turno.', 'How was your wait?': '¿Cómo fue la espera?', 'How was the service?': '¿Cómo fue el servicio?', 'Would you return?': '¿Volverías?', 'Submit anonymous rating': 'Enviar calificación anónima',
    'Queue joining hours': 'Horario para unirse a la cola', 'People can join only during these local times. After the end time, you may still finish serving people already in line.': 'Las personas solo pueden unirse durante este horario local. Después, aún puedes atender a quienes ya están en la fila.', 'The ticket closes after the first no-show.': 'El turno se cierra después de la primera ausencia.', 'The ticket keeps its number. After two deferrals, the third no-show closes it.': 'El turno conserva su número. Después de dos aplazamientos, la tercera ausencia lo cierra.', 'Use this for a short grace period before the ticket is recalled.': 'Úsalo para dar un breve tiempo de gracia antes de volver a llamar el turno.',
    'PAIR STAFF DEVICE': 'VINCULAR DISPOSITIVO DEL PERSONAL', 'Give staff queue access': 'Dar acceso al personal', 'Use this on the staff member’s device so they can call tickets without signing in to your personal account.': 'Úsalo en el dispositivo del personal para que pueda llamar turnos sin iniciar sesión en tu cuenta personal.', 'Scan with the staff device. This pairing QR expires in 10 minutes and works once.': 'Escanéalo con el dispositivo del personal. Este QR vence en 10 minutos y funciona una sola vez.', 'Or enter this PIN': 'O escribe este PIN', 'Revoke devices': 'Quitar dispositivos',
    'HOST · PRINT QUEUE QR': 'ANFITRIÓN · IMPRIMIR QR DE LA COLA', 'Print a scan-to-join sheet': 'Imprimir una hoja para escanear y unirse', 'Choose the paper size, then print the QR sheet for people waiting in line.': 'Elige el tamaño de papel y descarga la hoja QR para las personas que esperan.', 'Print sheet': 'Imprimir hoja',
    'PRIVACY PROMISE': 'COMPROMISO DE PRIVACIDAD', 'PUBLIC VERSION': 'VERSIÓN PÚBLICA', 'Join a queue without handing over your identity.': 'Únete a una cola sin entregar tu identidad.', 'For queuers:': 'Para clientes:', 'Clearly labelled ads.': 'Anuncios claramente identificados.', 'Minimal ticket data.': 'Datos mínimos del turno.', 'Anonymous ratings.': 'Calificaciones anónimas.', 'Optional notifications.': 'Notificaciones opcionales.', 'Private notes are optional.': 'Las notas privadas son opcionales.', 'Privacy choices': 'Opciones de privacidad',
    'Let’s Q does not ask for a name, phone number, email address, contact list, or social-media login. Your ticket uses only a queue number and a secret code that you choose.': 'Let’s Q no pide nombre, teléfono, correo electrónico, contactos ni acceso a redes sociales. Tu turno usa solo un número de cola y un código secreto que tú eliges.', 'The free Android app can show Google AdMob ads. Depending on your region, Google may ask for consent and offers Privacy choices where required.': 'La aplicación Android gratuita puede mostrar anuncios de Google AdMob. Según tu región, Google puede solicitar consentimiento y ofrecer opciones de privacidad cuando sea necesario.', 'Host analytics use aggregate rating scores only. Do not include names, contact details, ticket codes, or device identifiers in the report.': 'Los análisis del anfitrión usan solo puntuaciones agregadas. No incluyen nombres, datos de contacto, códigos de turno ni identificadores del dispositivo.',
    'Your ticket': 'Tu turno', 'JOIN THIS QUEUE': 'UNIRSE A ESTA COLA', 'Queue is full': 'La cola está llena', 'Queue is empty.': 'La cola está vacía.', 'UP NEXT': 'SIGUIENTE', 'ACTIVE': 'ACTIVO', 'Ticket details hidden until called': 'Los detalles del turno están ocultos hasta que te llamen', 'VISIT COMPLETE': 'VISITA TERMINADA', 'Thanks for visiting.': 'Gracias por tu visita.', 'Your anonymous rating was added to the aggregate report.': 'Tu calificación anónima se añadió al informe agregado.', 'Would you like to rate the wait and service?': '¿Quieres calificar la espera y el servicio?', 'View rating': 'Ver calificación',
    'YOUR TURN — head to the counter': 'ES TU TURNO — ve al mostrador', 'PLEASE COME TO THE COUNTER': 'POR FAVOR, ACÉRCATE AL MOSTRADOR', 'HELD — WE WILL CALL YOU AGAIN': 'EN ESPERA — TE LLAMAREMOS DE NUEVO', 'TICKET CANCELLED': 'TURNO CANCELADO', 'WAITING —': 'ESPERANDO —', 'est. wait': 'espera estimada', 'ahead': 'por delante', 'now': 'ahora', 'held': 'en espera', 'Share ticket by QR': 'Compartir turno por QR',
    'HOST CONSOLE': 'PANEL DEL ANFITRIÓN', 'Called ticket code:': 'Código del turno llamado:', 'View analytics': 'Ver análisis', 'Ad-free active': 'Sin anuncios activo', 'Ad-free + analytics · $1/month': 'Sin anuncios + análisis · $1/mes', 'Nobody is waiting.': 'No hay nadie esperando.', 'Saved queue': 'Cola guardada', 'Total queued': 'Total en cola', 'Avg. wait': 'Espera prom.', 'No-show rate': 'Tasa de ausencias', 'Anonymous experience ratings': 'Calificaciones anónimas', 'No ratings submitted yet.': 'Aún no hay calificaciones.', 'Back to host': 'Volver al anfitrión', 'Start a new queue': 'Iniciar una nueva cola', 'End queue': 'Cerrar cola', 'QR code': 'Código QR', 'Live queue code:': 'Código de cola en vivo:',
    'No full-screen ads are shown when the app opens.': 'No se muestran anuncios de pantalla completa al abrir la aplicación.', 'This device is ad-free.': 'Este dispositivo no tiene anuncios.', 'Go ad-free, with analytics included.': 'Usa la aplicación sin anuncios, con análisis incluidos.', 'Thank you. Your anonymous rating was added.': 'Gracias. Se añadió tu calificación anónima.', 'Choose one score for each question.': 'Elige una puntuación para cada pregunta.',
    'Join again': 'Unirse de nuevo', 'Cancel my ticket': 'Cancelar mi turno', 'Joining is closed': 'La cola está cerrada', 'Queue has not opened yet': 'La cola todavía no abre', 'Queue is no longer accepting new tickets.': 'Esta cola ya no acepta nuevos turnos.', 'Secret code': 'Código secreto', 'Optional request to booth': 'Solicitud opcional para el puesto', 'Join queue': 'Unirse a la cola', 'Call next': 'Llamar al siguiente', 'Present': 'Presente', 'Skip': 'Saltar', 'No-show': 'Ausente', 'Queue settings': 'Configuración de la cola', 'Pair staff device': 'Vincular dispositivo del personal', 'Back': 'Volver', 'Privacy choices are available in the Android app.': 'Las opciones de privacidad están disponibles en la aplicación Android.', 'Subscriptions are available in the Android app through Google Play.': 'Las suscripciones están disponibles en la aplicación Android mediante Google Play.'
  };
  const shellCompleteness = {
    ko: {
      'Host': '호스트', 'Join a queue': '대기열 참여', 'Set up a queue': '대기열 만들기', 'App appearance': '앱 외관', 'Your privacy comes first': '개인정보가 우선입니다.', 'Take a photo': '사진 촬영', 'Choose from device': '기기에서 선택', 'Start camera scanner': '카메라 스캔 시작', 'Cancel immediately': '즉시 취소', 'Start this queue': '이 대기열 시작', 'Home': '홈', 'Language': '언어', 'Notifications': '알림'
    },
    ja: {
      'Host': '主催者', 'Join a queue': '待機列に参加', 'Set up a queue': '待機列を作成', 'App appearance': 'アプリの外観', 'Your privacy comes first': 'プライバシーを最優先します。', 'Take a photo': '写真を撮る', 'Choose from device': '端末から選ぶ', 'Start camera scanner': 'カメラで読み取る', 'Cancel immediately': 'すぐに取り消す', 'Start this queue': 'この待機列を開始', 'Home': 'ホーム', 'Language': '言語', 'Notifications': '通知'
    }
  };
  Object.assign(translations.ko, ko, appCopy.ko);
  Object.assign(translations.ja, ja, appCopy.ja);
  Object.assign(translations['zh-Hant'], appCopy['zh-Hant']);
  Object.assign(translations['zh-Hans'] || (translations['zh-Hans'] = {}), appCopy['zh-Hans']);
  Object.assign(translations.es || (translations.es = {}), appCopy.es, legacySpanishCopy);
  Object.assign(translations.ko, shellCompleteness.ko);
  Object.assign(translations.ja, shellCompleteness.ja);
  window.render?.();
  window.localizePage?.();
})();
